### PR TITLE
Report percentages from original size

### LINKED ISSUE #31: % change value is incorrect
If you have a 1KB file, reduced by 0.5KB, it reports the change as `100%` rather than `50%`. 

[This line](https://github.com/preactjs/compressed-size-action/blob/master/src/utils.js#L129) needs to use the original size as the divisor, so `delta + size` rather than `size`.

### PR DESCRIPTION
**Pull request by arendjr**
Fixes #31.

### CODE REVIEW

File: src/utils.js [hunk 1]
```diff
@@ -41,30 +41,37 @@ export function stripHash(regex) {
...
-	else if (difference >= 20) icon = '🚨';
-	else if (difference >= 10) icon = '⚠️';
-	else if (difference >= 5) icon = '🔍';
-	else if (difference <= -50) icon = '🏆';
-	else if (difference <= -20) icon = '🎉';
-	else if (difference <= -10) icon = '👏';
-	else if (difference <= -5) icon = '✅';
-	return icon;
+export function iconForDifference(delta, originalSize) {
+	if (originalSize === 0) return '🆘';
```
Comment (bartlomiejzuber) [inline src/utils.js:63]: Could you please explain what is this statement for ? If `originalSize` is 0 then it will show as 🆘 which doesn't seem correct to me.

Comment (arendjr) [reply src/utils.js:63]: The original size is 0 when it's a new file, which is an infinite size increase for that file... So that's why it shows the SOS.

File: src/utils.js [hunk 2]
```diff
@@ -41,30 +41,37 @@ export function stripHash(regex) {
...
 	let deltaText = (delta > 0 ? '+' : '') + prettyBytes(delta);
-	if (delta && Math.abs(delta) > 1) {
-		deltaText += ` (${Math.abs(difference)}%)`;
+	if (originalSize === 0) {
+		deltaText += ` (new file)`;
+	} else if (originalSize === -delta) {
+		deltaText += ` (removed)`;
+	} else if (Math.abs(delta) > 0) {
+		const percentage = Math.round((delta / originalSize) * 100);
+		deltaText += ` (${delta > 0 ? '+' : '-'}${Math.abs(percentage)}%)`;
```
Comment (developit) [inline src/utils.js:54]: can just let toString add the `-`:

```suggestion
		deltaText += ` (${delta > 0 ? '+' : ''}${percentage}%)`;
```

File: src/utils.js (hunk 1 above)
Comment (developit) [reply src/utils.js:63]: I'd prefer a different icon for this:

```suggestion
	if (originalSize === 0) return '🆕';
```

**Review by developit — APPROVED** [review]
LGTM, just a couple minor suggestions I'd like to apply if that's alright with you.

**Comment by arendjr** [comment]
Cool 👍
